"use client";
import "./globals.css";

import { AppContextWrapper } from "./AppContextWrapper";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
const queryClient = new QueryClient()

// export const metadata = {
//   title: "myFlavour - by Fimiar",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <body>
          <AppContextWrapper>{children}</AppContextWrapper>
        </body>
      </QueryClientProvider>
    </html>
  );
}
